<?php

/**
 * @file
 * Contains the module file for the Obama SOAP Webservice.
 */

/**
 * Implements hook_theme().
 *
 * Since we have a lot to explain, we're going to use Twig to do it.
 */
function obama_soap_webservice_theme() {
  return [
    'publicatie_service' => [
      'template' => 'publicatie_service',
      'variables' => [
        'xsd_url' => NULL,
        'service_endpoint' => NULL,
      ],
    ],
  ];
}
